NEW_COIN="potato"

mv  innova-docs/ ${NEW_COIN}-docs/
mv contrib/innovad.bash-completion contrib/${NEW_COIN}d.bash-completion
mv contrib/innova-qt.pro contrib/${NEW_COIN}-qt.pro
mv contrib/debian/innovad.bash-completion contrib/debian/${NEW_COIN}d.bash-completion
mv contrib/debian/innovad.examples contrib/debian/${NEW_COIN}d.examples
mv contrib/debian/innovad.install contrib/debian/${NEW_COIN}d.install
mv contrib/debian/innovad.lintian-overrides contrib/debian/${NEW_COIN}d.lintian-overrides
mv contrib/debian/innovad.manpages contrib/debian/${NEW_COIN}d.manpages
mv contrib/debian/innova-qt.desktop.desktop contrib/debian/${NEW_COIN}-qt.desktop.desktop
mv contrib/debian/innova-qt.install contrib/debian/${NEW_COIN}-qt.install
mv contrib/debian/innova-qt.lintian-overrides contrib/debian/${NEW_COIN}-qt.lintian-overrides
mv contrib/debian/innova-qt.protocol contrib/debian/${NEW_COIN}-qt.protocol
mv contrib/debian/innova-tx.install contrib/debian/${NEW_COIN}-tx.install
mv contrib/debian/examples/innova.conf contrib/debian/examples/${NEW_COIN}.conf
mv contrib/debian/manpages/innova.conf.5 contrib/debian/manpages/${NEW_COIN}.conf.5
mv contrib/debian/manpages/innova-cli.1 contrib/debian/manpages/${NEW_COIN}-cli.1
mv contrib/debian/manpages/innovad.1 contrib/debian/manpages/${NEW_COIN}d.1
mv contrib/debian/manpages/innova-qt.1 contrib/debian/manpages/${NEW_COIN}-qt.1
mv contrib/init/innovad.conf contrib/init/${NEW_COIN}d.conf
mv contrib/init/innovad.init contrib/init/${NEW_COIN}d.init
mv contrib/init/innovad.openrc contrib/init/${NEW_COIN}d.openrc
mv contrib/init/innovad.openrcconf contrib/init/${NEW_COIN}d.openrcconf
mv contrib/init/innovad.service contrib/init/${NEW_COIN}d.service
mv contrib/init/org.innova.innovad.plist contrib/init/org.${NEW_COIN}.${NEW_COIN}d.plist
mv share/pixmaps/innova16.png share/pixmaps/${NEW_COIN}16.png
mv share/pixmaps/innova16.xpm share/pixmaps/${NEW_COIN}16.xpm
mv share/pixmaps/innova32.png share/pixmaps/${NEW_COIN}32.png
mv share/pixmaps/innova32.xpm share/pixmaps/${NEW_COIN}32.xpm
mv share/pixmaps/innova64.png share/pixmaps/${NEW_COIN}64.png
mv share/pixmaps/innova64.xpm share/pixmaps/${NEW_COIN}64.xpm
mv share/pixmaps/innova128.png share/pixmaps/${NEW_COIN}128.png
mv share/pixmaps/innova128.xpm share/pixmaps/${NEW_COIN}128.xpm
mv share/pixmaps/innova256.png share/pixmaps/${NEW_COIN}256.png
mv share/pixmaps/innova256.xpm share/pixmaps/${NEW_COIN}256.xpm
mv src/bench/bench_innova.cpp src/bench/bench_${NEW_COIN}.cpp
mv src/config/innova-config.h src/config/${NEW_COIN}-config.h
mv src/qt/innova.cpp src/qt/${NEW_COIN}.cpp
mv src/qt/innova.qrc src/qt/${NEW_COIN}.qrc
mv src/qt/innova_locale.qrc src/qt/${NEW_COIN}_locale.qrc
mv src/qt/innovastrings.cpp src/qt/${NEW_COIN}strings.cpp
mv src/qt/locale/innova_bg.ts src/qt/locale/${NEW_COIN}_bg.ts
mv src/qt/locale/innova_de.ts src/qt/locale/${NEW_COIN}_de.ts
mv src/qt/locale/innova_en.ts src/qt/locale/${NEW_COIN}_en.ts
mv src/qt/locale/innova_es.ts src/qt/locale/${NEW_COIN}_es.ts
mv src/qt/locale/innova_fi.ts src/qt/locale/${NEW_COIN}_fi.ts
mv src/qt/locale/innova_fr.ts src/qt/locale/${NEW_COIN}_fr.ts
mv src/qt/locale/innova_it.ts src/qt/locale/${NEW_COIN}_it.ts
mv src/qt/locale/innova_ja.ts src/qt/locale/${NEW_COIN}_ja.ts
mv src/qt/locale/innova_pl.ts src/qt/locale/${NEW_COIN}_pl.ts
mv src/qt/locale/innova_pt.ts src/qt/locale/${NEW_COIN}_pt.ts
mv src/qt/locale/innova_ru.ts src/qt/locale/${NEW_COIN}_ru.ts
mv src/qt/locale/innova_sk.ts src/qt/locale/${NEW_COIN}_sk.ts
mv src/qt/locale/innova_sv.ts src/qt/locale/${NEW_COIN}_sv.ts
mv src/qt/locale/innova_vi.ts src/qt/locale/${NEW_COIN}_vi.ts
mv src/qt/locale/innova_zh_CN.ts src/qt/locale/${NEW_COIN}_zh_CN.ts
mv src/qt/locale/innova_zh_TW.ts src/qt/locale/${NEW_COIN}_zh_TW.ts
mv src/qt/res/images/crownium/innova_logo_horizontal.png src/qt/res/images/crownium/${NEW_COIN}_logo_horizontal.png
mv src/qt/res/images/drkblue/innova_logo_horizontal.png src/qt/res/images/drkblue/${NEW_COIN}_logo_horizontal.png
mv src/qt/res/images/light/innova_logo_horizontal.png src/qt/res/images/light/${NEW_COIN}_logo_horizontal.png
mv src/qt/res/images/trad/innova_logo_horizontal.png src/qt/res/images/trad/${NEW_COIN}_logo_horizontal.png
mv src/qt/res/innova-qt-res.rc src/qt/res/${NEW_COIN}-qt-res.rc
mv src/test/test_innova.cpp src/test/test_${NEW_COIN}.cpp
mv src/test/test_innova.h src/test/test_${NEW_COIN}.h
mv src/innova-cli.cpp src/${NEW_COIN}-cli.cpp
mv src/innova-cli-res.rc src/${NEW_COIN}-cli-res.rc
mv src/innovad.cpp src/${NEW_COIN}d.cpp
mv src/innovad-res.rc src/${NEW_COIN}d-res.rc
mv src/innova-tx.cpp src/${NEW_COIN}-tx.cpp
mv src/innova-tx-res.rc src/${NEW_COIN}-tx-res.rc
